blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/MrXploisLite/RimWorld-Mod-Manager-for-Arch-Linux/discussions
    about: Ask questions and discuss ideas
  - name: ðŸ“– Wiki
    url: https://github.com/MrXploisLite/RimWorld-Mod-Manager-for-Arch-Linux/wiki
    about: Check the wiki for documentation
